### ISSUE TITLE
label_position error

### ISSUE THREAD

**Issue by ese-jdm418** [yorgath/orthogram#1]
Hi,

I have been trying to use the label_position option when using d_add_bloc. The line of code I have used is imaged below:

![image](https://user-images.githubusercontent.com/57348351/125258049-e3b3ac00-e2f5-11eb-8a1f-87fd082e163c.png)

However when I do this an error occurs that I am not sure how to fix. I have provided a screenshot of the error message below. It would be great if someone could help as I am trying to visualise some stocks and flow data. 

![image](https://user-images.githubusercontent.com/57348351/125258152-f8903f80-e2f5-11eb-81f3-4ea28e7ed234.png)

Just so you know here are all my libraries installed:

attrs                     21.2.0             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
bottleneck                1.3.2            py39h7cc1a96_1
ca-certificates           2021.7.5             haa95532_1
cassowary                 0.5.2                    pypi_0    pypi
certifi                   2021.5.30        py39haa95532_0
colorama                  0.4.4              pyhd3eb1b0_0
cycler                    0.10.0           py39haa95532_0
decorator                 4.4.2                    pypi_0    pypi
et_xmlfile                1.1.0            py39haa95532_0
freetype                  2.10.4               hd328e21_0
geos                      3.8.0                h33f27b4_0
icu                       58.2                 ha925a31_3
importlib-metadata        3.10.0           py39haa95532_0
importlib_metadata        3.10.0               hd3eb1b0_0
intel-openmp              2021.2.0           haa95532_616
ipykernel                 5.3.4            py39h7b7c402_0
ipython                   7.22.0           py39hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jdcal                     1.4.1                      py_0
jedi                      0.17.2           py39haa95532_1
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                      py_2
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.7.1            py39haa95532_0
kiwisolver                1.3.1            py39hd77b12b_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libtiff                   4.2.0                hd0e1b90_0
lz4-c                     1.9.3                h2bbff1b_0
matplotlib                3.3.4            py39haa95532_0
matplotlib-base           3.3.4            py39h49ac443_0
mkl                       2021.2.0           haa95532_296
mkl-service               2.3.0            py39h2bbff1b_1
mkl_fft                   1.3.0            py39h277e83a_2
mkl_random                1.2.1            py39hf11a4ad_2
nbformat                  5.1.3              pyhd3eb1b0_0
networkx                  2.5.1                    pypi_0    pypi
numexpr                   2.7.3            py39hb80d3ca_1
numpy                     1.20.2           py39ha4e8547_0
numpy-base                1.20.2           py39hc2deb75_0
olefile                   0.46                       py_0
openpyxl                  3.0.7              pyhd3eb1b0_0
openssl                   1.1.1k               h2bbff1b_0
orthogram                 0.5.4                    pypi_0    pypi
pandas                    1.2.5            py39hd77b12b_0
parso                     0.7.0                      py_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.2.0            py39h4fa10fc_0
pip                       21.1.3           py39haa95532_0
plotly                    5.1.0                      py_0    plotly
prompt-toolkit            3.0.17             pyh06a4308_0
pycairo                   1.20.1                   pypi_0    pypi
pygments                  2.9.0              pyhd3eb1b0_0
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py39hd77b12b_6
pyrsistent                0.18.0           py39h2bbff1b_0
python                    3.9.5                h6244533_3
python-dateutil           2.8.1              pyhd3eb1b0_0
pytz                      2021.1             pyhd3eb1b0_0
pywin32                   228              py39he774522_0
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     20.0.0           py39hd77b12b_1
qt                        5.9.7            vc14h73c81de_0
setuptools                52.0.0           py39haa95532_0
shapely                   1.7.0            py39h06580b3_0
sip                       4.19.13          py39hd77b12b_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               h2bbff1b_0
tenacity                  7.0.0            py39haa95532_0
tk                        8.6.10               he774522_0
tornado                   6.1              py39h2bbff1b_0
traitlets                 5.0.5              pyhd3eb1b0_0
types-pyyaml              5.4.3                    pypi_0    pypi
tzdata                    2021a                h52ac0ba_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                      py_0
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2              py39h2bbff1b_0
xlrd                      2.0.1              pyhd3eb1b0_0
xz                        5.2.5                h62dcd97_0
zeromq                    4.3.3                ha925a31_3
zipp                      3.5.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.9                h19a0ad4_0

Using Python version 3.9.5

Thanks in advance for any help.

**Comment by yorgath** [comment]
Hi there,

Try using the enumerated value instead:

```python
from orthogram import LabelPosition

d.add_block(..., label_position=LabelPosition.TOP)
```

Cheers,
yorgath

**Comment by ese-jdm418** [comment]
Hi Yorgath,

                    I just tried your solution and it has worked. Thank you very much for helping!

John
